// babel.config.js — AUTO-GENERATED by AI Test Quality Agent
// Handles JSX, React, and ES Modules (import/export).
// Requires: npm install --save-dev @babel/core @babel/preset-env @babel/preset-react babel-jest
module.exports = {
  presets: [
    ['@babel/preset-env', { targets: { node: 'current' }, modules: 'commonjs' }],
    ['@babel/preset-react', { runtime: 'automatic' }],
  ],
};
