// jest.config.js — AUTO-GENERATED by AI Test Quality Agent
// testEnvironment: jsdom — required for React Testing Library and DOM APIs.
// transform: babel-jest — required to handle JSX and ES module imports.
// Requires: npm install --save-dev jest-environment-jsdom @testing-library/react @testing-library/jest-dom
module.exports = {
  testEnvironment: 'jsdom',
  testMatch: [
    '**/tests/**/*.test.js',
    '**/tests/**/*.spec.js',
  ],
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
  collectCoverageFrom: [
    'flask_app/**/*.{js,jsx}',
    '!**/__mocks__/**',
    '!**/node_modules/**',
  ],
  coverageProvider: 'v8',
};
