# conftest.py — AUTO-GENERATED by AI Test Quality Agent
import sys
from unittest.mock import MagicMock

_es_mock = MagicMock()
try:
    import elasticsearch as _real_es
    _es_mock.exceptions = _real_es.exceptions
except Exception:
    pass
sys.modules["elasticsearch"] = _es_mock
sys.modules["requests"] = MagicMock()
sys.modules["requests.adapters"] = MagicMock()
sys.modules["requests.models"] = MagicMock()
