// AUTO-GENERATED by AI Test Quality Agent
// Generic manual mock for got
module.exports = {
  get:  jest.fn().mockResolvedValue({ body: '{}', statusCode: 200 }),
  post: jest.fn().mockResolvedValue({ body: '{}', statusCode: 201 }),
  put:  jest.fn().mockResolvedValue({ body: '{}', statusCode: 200 }),
};
