// AUTO-GENERATED by AI Test Quality Agent
// Generic manual mock for node-fetch
module.exports = jest.fn().mockResolvedValue({
  ok: true,
  status: 200,
  json: jest.fn().mockResolvedValue({}),
  text: jest.fn().mockResolvedValue(''),
});
