// AUTO-GENERATED by AI Test Quality Agent
// Generic manual mock for superagent.
// end() calls the callback with (null, {body:{}}) by default so
// the function body is executed and coverage is measured.
// Override per test: request.get.mockReturnValue({end: jest.fn(cb => cb(null, res))})
const _makeChain = (body = {}) => ({
  set:    jest.fn().mockReturnThis(),
  query:  jest.fn().mockReturnThis(),
  send:   jest.fn().mockReturnThis(),
  accept: jest.fn().mockReturnThis(),
  end:    jest.fn().mockImplementation((cb) => {
    // Async callback: allows React to batch setState before callback executes
    setImmediate(() => cb(null, { body, status: 200 }));
  }),
});
const mockRequest = {
  get:    jest.fn().mockImplementation(() => _makeChain()),
  post:   jest.fn().mockImplementation(() => _makeChain()),
  put:    jest.fn().mockImplementation(() => _makeChain()),
  patch:  jest.fn().mockImplementation(() => _makeChain()),
  delete: jest.fn().mockImplementation(() => _makeChain()),
};
module.exports = mockRequest;
